---
output:
  html_document:
    toc: false
editor_options: 
  chunk_output_type: console
---

### Домашнее задание 2 (до 20.02.2018)
Домашнее задание нужно выполнять в отдельном `rmarkdown` файле, скачав данные [из своей папки](https://github.com/agricolamz/2018_data_analysis_for_linguists/tree/master/data/students) в репозитории курса. Получившиеся файлы следует помещать в соответствующую папку в своем репозитории на гитхабе. Более подробные инструкции [см. на этой странице](https://agricolamz.github.io/2018_data_analysis_for_linguists/index.html).

#### 1.1
Скачайте датасет `hw1_1_zilo_class.csv` (см. описание выше). Получите тиббл содержащий два столбца: `stimulus_source` и количество уникальных слов в датасете (`n`).

#### 1.2
Преобразуйте датасет `hw1_1_zilo_class.csv`. Посчитайте процент полного согласия всех спикеров.

#### 1.3
Из преобразованным датасета `hw1_1_zilo_class.csv` выберите спикеров с номером `7` и `11` и посчитайте для них каппу Коэна.

#### 1.4
Посчитайте каппу Фляйса для всех спикеров преобразованного датасета `hw1_1_zilo_class.csv`.

#### 1.5
Представим, что Вы пишите статью, напишите короткий абзац, который бы обобщал результаты, полученные в предыдущих заданиях.

#### 2.1
Скачайте датасет `hw1_2_verbs.csv` (см. описание выше). Посчитайте количество участников в датасете (в ответ выведите тибл с переменной `n`).

#### 2.2
Посчитайте среднюю оценку глаголов разного типа для каждого пола в датасете (в ответ выведите тибл с переменными `WordType`, `Gender` и `mean`).

#### 2.3
Преобразуйте датасет в короткий формат и удалите строки, в которых есть пропущенные значения (у меня вышел тибл 59 x 124). Посчитайте процент полного согласия.

#### 2.4
Посчитайте каппу Фляйса для преобразованного датасета.

#### 2.5
Посчитайте ICC для преобразованного датасета.

#### 2.6
Создайте тибл, содержащий минимальное (`min`) и максимальное (`max`) значение попарной корреляции Кендала ответов всех участников эксперимента со словами (т. е. корреляция ответов `АА` и `AB`, `AA` и `AC` и т. д.). В преобразовании матрицы, пораждаемой функцией `cor()` мне очень помогла функция `as.table()`.
