---
output:
  html_document:
    toc: false
editor_options: 
  chunk_output_type: console
---

### Домашнее задание 3 (до 27.02.2018)
Домашнее задание нужно выполнять в отдельном `rmarkdown` файле, скачав данные [из своей папки](https://github.com/agricolamz/2018_data_analysis_for_linguists/tree/master/data/students) в репозитории курса. Получившиеся файлы следует помещать в соответствующую папку в своем репозитории на гитхабе. Более подробные инструкции [см. на этой странице](file:///home/agricolamz/work/materials/2018_I_HSE_Data_Analysis_for_linguists/docs/index.html).

В вашей папке ледит файл с тремя значениями: $n$ --- количество попыток, $k$ --- количество успехов, $prior$ ---  наши предворительные идеи относительно доли успехов.

#### 1.1
Приведите результаты биномиального теста.

#### 1.2
Приведите результаты симуляции, используя `set.seed(42)`.

#### 1.3
Приведите среднее апостериорного распределения, используя $prior$  как средние априорного распределения, а $n$ как количество элементов для вычисления апостериорного распределения.

#### 1.4
Приведите среднее апостериорного распределения, используя неинформативное априорное распределение.

#### 1.5
Представим, что Вы пишите статью, напишите короткий абзац, который бы обобщал результаты, полученные в предыдущих заданиях. Не забывайте приводить результаты статистических тестов.
