---
output:
  html_document:
    toc: false
editor_options: 
  chunk_output_type: console
---

### Домашнее задание 4 (до 06.03.2018)
Домашнее задание нужно выполнять в отдельном `rmarkdown` файле, скачав данные [из своей папки](https://github.com/agricolamz/2018_data_analysis_for_linguists/tree/master/data/students) в репозитории курса. Получившиеся файлы следует помещать в соответствующую папку в своем репозитории на гитхабе. Более подробные инструкции [см. на этой странице](https://agricolamz.github.io/2018_data_analysis_for_linguists/index.html).

В вашей папке ледит файл с главами из текста романа П. Г. Вудхауза “Фамильная честь Вустеров” со следующими переменными

* `chapter` --- номер главы
* `linenumber` ---  номер абзаца в тексте\
* `word` --- слово из текста. Слова в строках идут по порядку, так же как они идут в тексте.

#### 1.1
Посчитайте среднее употребление слова "сэр" по каждой главе, а потом посчитайте grand mean. Ответ выведите в формате тиббл.

#### 1.2
Посчитайте бутстрэпом доверительный интервал для средней доли слова "сэр" в главах романа и выведите его размер в формате тиббл.

#### 1.3
Посчитайте биномиальный доверительный интервал употребления слова "сэр" в каждой главе и выведите главу с максимальным из интервалов в формате тиббл.

#### 1.4
Посчитайте байесовский биномиальный доверительный интервал употребления слова "сэр" в каждой главе и выведите главу с максимальным из интервалов в формате тиббл.

#### 1.5
Посчитайте биномиальный доверительный интервал употребления слова "сэр" в каждой главе и выведите главу с минимальным из интервалов в формате тиббл.

#### 1.6
Посчитайте байесовский биномиальный доверительный интервал употребления слова "сэр" в каждой главе и выведите главу с минимальным из интервалов в формате тиббл.

#### 1.7
Напишите короткий текст, комментирующий наблюдаемые сходства/различия между оценками среднего и доверительных интервалов количества употреблений слова "сэр" во всех главах романа. Что можно сказать про разные главы? Что можно сказать о сходстве/различиях фриквентистсткой и байесовской оценок наблюдаемых параметров?

