---
title: "Анализ Данных для лингвистов"
author: "Г. Мороз"
output:
  html_document:
    toc: false
---

### Библиотеки:
```{r, message=FALSE}
packageVersion("tidyverse")
packageVersion("readxl")
packageVersion("mosaic")
packageVersion("stringr")
packageVersion("bootstrap")
packageVersion("irr")
packageVersion("ca")
packageVersion("MASS")
```

### Как выполнять домашние задания?
Домашние задания у всех общие, однако для каждого студента каждый датасет несколько отличается. Все датасеты собраны в [этой папке](https://goo.gl/TJ3t8j), где содержатся подпапки для каждого студента (если, Вы не видете Вашей папки, заполните [эту форму](https://goo.gl/forms/IYnkfSPauEJPf9SG3) и напишите мне).

Домашние задания будут проверятся полуавтоматически, так что пожалуйста:

* создайте репозиторий `2018_hse_data_analysis` (или переименуйте уже существующий);
* следуйте паттерну называния подпапок повторяющему [схему в Вашей папке](https://github.com/agricolamz/2018_data_analysis_for_linguists/tree/master/data/students) в репозитории курса;
```{bash, echo = FALSE, comment = ""}
cd /home/agricolamz/work/materials/2018_I_HSE_Data_Analysis_for_linguists/data/students/sandrasimdi
tree
```

* добавьте в соответствующую папку файл с решением в формате `.Rmd` (желательно без кириллицы в названии);
* фрагменты кода, посвященные отдельным заданиям разделяйте заголовками третьего уровня, пробелом и номером задания "### 1.1", "### 1.2", "### 2.1" и т. д. При этом, пожалуйста больше нигде в коде три и больше знака решётки подряд не используйте;
* фрагменты кода, посвященные конкретным заданиям должны выводить ответ в консоль.
