<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Г. Мороз" />


<title></title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 52px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 57px;
  margin-top: -57px;
}

.section h2 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h3 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h4 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h5 {
  padding-top: 57px;
  margin-top: -57px;
}
.section h6 {
  padding-top: 57px;
  margin-top: -57px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    tidyverse
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_tidyverse.html">1. tidyverse</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    меры согласия
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_agreement.html">2. Меры согласия</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    биномиальные данные
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="3_binomial.html">3. Биномиальные данные</a>
    </li>
    <li>
      <a href="4_binomial_ci.html">4. Binomial CI</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    уменьшение размерности
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="5_PCA.html">5. PCA</a>
    </li>
    <li>
      <a href="6_CA_MCA.html">6. CA, MCA</a>
    </li>
    <li>
      <a href="7_Clustering.html">7. Кластеризация</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    регрессия
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="8_regression.html">8. Ограничения на применения регрессии</a>
    </li>
    <li>
      <a href="9_mixed_effects.html">9. Регрессия со смешанными эффектами</a>
    </li>
    <li>
      <a href="10_nolinear.html">9. Нелинейная регрессия</a>
    </li>
    <li>
      <a href="11_ridge_lasso.html">11. Ридж и лассо регрессия</a>
    </li>
    <li>
      <a href="12_gradient_boosting.html">12. Градиентный спуск</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore"><ol start="5" style="list-style-type: decimal">
<li>Уменьшение размерности: PCA</li>
</ol></h1>
<h4 class="author"><em>Г. Мороз</em></h4>

</div>


<style>
.parallax {
    /* The image used */
    background-image: url("5_PCA.jpg");

    /* Set a specific height */
    min-height: 300px; 

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: auto;
}
</style>
<div class="parallax">

</div>
<div class="section level3">
<h3>1. Введение</h3>
<p>Метод главных компонент (PCA, Principal Component Analysis) применим к числовым данным, в которых строчки — это точки наблюдения, а столбцы — это исследуемые переменные. Данный метод часто приводят и используют как метод уменьшения размерности, однако я разделяю мнение, согласно которому это лишь метод смены перспективы, в результаты которого некоторое количество размерностей становится маловажными.</p>
<div class="section level4">
<h4>1.1 Библиотеки</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre></div>
</div>
<div id="--" class="section level4">
<h4>1.2 Фамильная честь вустеров</h4>
<p>В данной лекции я буду использовать данные из романа П. Г. Вудхауза <a href="https://en.wikipedia.org/wiki/The_Code_of_the_Woosters">“Фамильная честь Вустеров”</a>. В датасете собраны несколько переменных:</p>
<ul>
<li>chapter — номер главы</li>
<li>гарольд — частотность появления имени в каждой из глав</li>
<li>гасси — частотность появления имени в каждой из глав</li>
<li>далия — частотность появления имени в каждой из глав</li>
<li>дживс — частотность появления имени в каждой из глав</li>
<li>мадлен — частотность появления имени в каждой из глав</li>
<li>оутс — частотность появления имени в каждой из глав</li>
<li>спод — частотность появления имени в каждой из глав</li>
<li>стиффи — частотность появления имени в каждой из глав</li>
<li>сэр — частотность появления имени в каждой из глав</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">wodehouse &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://goo.gl/Qux1gS&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)
<span class="kw">library</span>(GGally)
<span class="kw">ggpairs</span>(wodehouse[,<span class="op">-</span><span class="dv">1</span>])<span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="5_PCA_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="parallax">

</div>
</div>
</div>
<div id="---" class="section level3">
<h3>2. Дисперсия, ковариация, корреляция Пирсона</h3>
<p><span class="math display">\[var(X) = \frac{\sum_{i = 1}^n(x_i - \bar{x})^2}{n - 1}\]</span></p>
<p><span class="math display">\[cov(X, Y) = \frac{\sum_{i = 1}^n(x_i - \bar{x})(y_i-\bar{y})}{n - 1}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cov</span>(wodehouse[,<span class="op">-</span><span class="dv">1</span>])</code></pre></div>
<pre><code>##               гарольд         гасси         далия         дживс
## гарольд  2.386168e-06 -2.889885e-06 -1.460862e-06 -3.189492e-06
## гасси   -2.889885e-06  1.547471e-05 -2.408293e-07 -4.003681e-06
## далия   -1.460862e-06 -2.408293e-07  9.538701e-06  1.032326e-05
## дживс   -3.189492e-06 -4.003681e-06  1.032326e-05  3.876272e-05
## мадлен  -1.186985e-06  5.782058e-06 -3.263335e-06 -8.873167e-06
## оутс     4.253683e-07 -2.740335e-06  3.656516e-07  4.847624e-07
## спод    -3.171558e-06  1.192382e-05 -1.587378e-06 -4.324372e-06
## стиффи   5.852747e-06 -8.472296e-06 -5.377545e-06 -5.558223e-06
## сэр     -4.022204e-06 -8.049261e-06  9.348602e-06  5.202877e-05
##                мадлен          оутс          спод        стиффи
## гарольд -1.186985e-06  4.253683e-07 -3.171558e-06  5.852747e-06
## гасси    5.782058e-06 -2.740335e-06  1.192382e-05 -8.472296e-06
## далия   -3.263335e-06  3.656516e-07 -1.587378e-06 -5.377545e-06
## дживс   -8.873167e-06  4.847624e-07 -4.324372e-06 -5.558223e-06
## мадлен   6.637573e-06 -8.894871e-07  4.458108e-06 -3.836640e-06
## оутс    -8.894871e-07  2.221350e-06 -1.978200e-06  1.259601e-07
## спод     4.458108e-06 -1.978200e-06  2.287974e-05 -4.867900e-06
## стиффи  -3.836640e-06  1.259601e-07 -4.867900e-06  2.222599e-05
## сэр     -1.253736e-05  6.519538e-06 -8.919541e-06 -5.673706e-06
##                   сэр
## гарольд -4.022204e-06
## гасси   -8.049261e-06
## далия    9.348602e-06
## дживс    5.202877e-05
## мадлен  -1.253736e-05
## оутс     6.519538e-06
## спод    -8.919541e-06
## стиффи  -5.673706e-06
## сэр      9.960665e-05</code></pre>
<p><span class="math display">\[cor(X, Y) = \frac{cov(X, Y)}{\sigma_X\times\sigma_Y}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(wodehouse[,<span class="op">-</span><span class="dv">1</span>])</code></pre></div>
<pre><code>##            гарольд       гасси       далия       дживс     мадлен
## гарольд  1.0000000 -0.47557473 -0.30620632 -0.33163769 -0.2982566
## гасси   -0.4755747  1.00000000 -0.01982227 -0.16347111  0.5705142
## далия   -0.3062063 -0.01982227  1.00000000  0.53686514 -0.4101214
## дживс   -0.3316377 -0.16347111  0.53686514  1.00000000 -0.5531805
## мадлен  -0.2982566  0.57051424 -0.41012138 -0.55318053  1.0000000
## оутс     0.1847592 -0.46739478  0.07943545  0.05224121 -0.2316469
## спод    -0.4292365  0.63369266 -0.10745096 -0.14520796  0.3617599
## стиффи   0.8036716 -0.45683480 -0.36932510 -0.18936434 -0.3158754
## сэр     -0.2608972 -0.20502203  0.30328984  0.83732159 -0.4875926
##                оутс       спод      стиффи        сэр
## гарольд  0.18475920 -0.4292365  0.80367163 -0.2608972
## гасси   -0.46739478  0.6336927 -0.45683480 -0.2050220
## далия    0.07943545 -0.1074510 -0.36932510  0.3032898
## дживс    0.05224121 -0.1452080 -0.18936434  0.8373216
## мадлен  -0.23164689  0.3617599 -0.31587536 -0.4875926
## оутс     1.00000000 -0.2774829  0.01792643  0.4382926
## спод    -0.27748290  1.0000000 -0.21586665 -0.1868413
## стиффи   0.01792643 -0.2158666  1.00000000 -0.1205847
## сэр      0.43829256 -0.1868413 -0.12058465  1.0000000</code></pre>
<div class="parallax">

</div>
</div>
<div id="---" class="section level3">
<h3>3. Собственный вектор, собственное значение</h3>
<p>Как вы знаете матрицы можно перемножать. <a href="https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg">Подсказка</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)
m2 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)
m3 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)
m1</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    2    3
## [2,]    2    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m2</code></pre></div>
<pre><code>##      [,1]
## [1,]    1
## [2,]    3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1 <span class="op">%*%</span><span class="st"> </span>m2</code></pre></div>
<pre><code>##      [,1]
## [1,]   11
## [2,]    5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    2    3
## [2,]    2    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m3</code></pre></div>
<pre><code>##      [,1]
## [1,]    3
## [2,]    2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1 <span class="op">%*%</span><span class="st"> </span>m3</code></pre></div>
<pre><code>##      [,1]
## [1,]   12
## [2,]    8</code></pre>
<p>В первом примере мы получили матрицу <span class="math inline">\(\left(\array{11\\ 5}\right)\)</span>, а во втором случае <span class="math inline">\(\left(\array{12\\ 8}\right) = 4 \times \left(\array{3\\ 2}\right)\)</span>, т. е. при умножении матрицы мы получили значение, равное скалярному умножению той же самой матрицы.</p>
<p>Мы можем думать об одной матрице, как о векторе <span class="math inline">\(\left(\array{3\\ 2}\right)\)</span> в двумерном пространстве. Тогда матрица <span class="math inline">\(\left(\array{2 &amp; 3\\ 2 &amp; 1}\right)\)</span> — это матрица некоторой трансформации А, которая изменяет вектор <span class="math inline">\(\left(\array{3\\ 2}\right)\)</span>. В таком случае <strong>собственный вектор (eigenvector)</strong> — это тот постянный объект, который подвергается трансформации, а <strong>собственное значение (eigenvalues)</strong> — это скалярный мультипликатор собсвтенного вектора (в нашем случае собственное значение равно 4).</p>
<p>Свойства собсвтенных векторов:</p>
<ul>
<li>собственные векторы можно найти только для квадратных матриц (и то не для всех)</li>
<li>все собственные векторы матрицы перпендекулярны друг другу вне зависимости от размерности.</li>
<li>принято задавать собственные векторы длинной 1, так что найдя собственный вектор <span class="math inline">\(\left(\array{3\\ 2}\right)\)</span>, мы узнаем его длинну <span class="math display">\[\sqrt{3^2+2^2} = \sqrt{13},\]</span> так что теперь можно отмасштабировать вектор: <span class="math display">\[\left(\array{3\\ 2}\right) \times \frac{1}{\sqrt{13}} = \left(\array{3/\sqrt{13}\\ 2/\sqrt{13}}\right)\]</span></li>
</ul>
<p>Как найти собственный вектор в R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)
<span class="kw">eigen</span>(m)</code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  4 -1
## 
## $vectors
##           [,1]       [,2]
## [1,] 0.8320503 -0.7071068
## [2,] 0.5547002  0.7071068</code></pre>
<p>Собственные значения в переменной <code>values</code> функция всегда возвращает в убывающем порядке, а каждая колонка в переменной <code>eigenvectors</code> соответствует элементу в переменной <code>values</code>. Сравните со значениями, которые мы получили руками:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">3</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">13</span>)</code></pre></div>
<pre><code>## [1] 0.8320503</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">13</span>)</code></pre></div>
<pre><code>## [1] 0.5547002</code></pre>
<div class="parallax">

</div>
</div>
<div id="pca" class="section level3">
<h3>4. PCA</h3>
<p>Обычно переменные, которые используют в PCA <strong>нужно обязательно нормализовать</strong>, но так как мы будем использовать частотность, эти переменные не нуждаются в нормализации. Давайте сравним результат работы функций, которые мы рассмотрели перед этим и функции <code>prcomp</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">eigen</span>(<span class="kw">cov</span>(wodehouse[,<span class="op">-</span><span class="dv">1</span>]))</code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 1.356038e-04 4.015202e-05 1.845105e-05 1.246263e-05 6.075232e-06
## [6] 4.352082e-06 1.855247e-06 6.550470e-07 1.265038e-07
## 
## $vectors
##              [,1]        [,2]         [,3]        [,4]        [,5]
##  [1,]  0.03548428  0.19663999 -0.075686879 -0.03368713  0.05890242
##  [2,]  0.08477226 -0.51351224 -0.134539726  0.05377012  0.65708710
##  [3,] -0.11013760 -0.09840259  0.388433965 -0.43335718 -0.21220875
##  [4,] -0.48849572 -0.10100883  0.148787895 -0.57991681  0.28388407
##  [5,]  0.12377778 -0.18961709 -0.020354106  0.32039042  0.22010871
##  [6,] -0.04712363  0.06751616 -0.004473342  0.20678545 -0.34253505
##  [7,]  0.09814424 -0.55844483 -0.599469737 -0.29899851 -0.45659562
##  [8,]  0.05838698  0.56967373 -0.609313517 -0.30930782  0.24922420
##  [9,] -0.84274152 -0.02915765 -0.268496830  0.37601904 -0.05266838
##              [,6]        [,7]        [,8]        [,9]
##  [1,]  0.14492413  0.11925658  0.73875236  0.60725660
##  [2,]  0.43845894  0.19560719  0.10480039 -0.18673960
##  [3,]  0.65127401 -0.36616001 -0.12101985  0.14696227
##  [4,] -0.43803831 -0.09265465  0.27430311 -0.19087430
##  [5,] -0.20367150 -0.85162955  0.09852740  0.14404733
##  [6,]  0.21240113 -0.13343752  0.55755002 -0.67773786
##  [7,] -0.09036398 -0.03379965  0.04752482  0.09847218
##  [8,]  0.20775743 -0.24593603 -0.12571229 -0.15350747
##  [9,]  0.18108076 -0.01233863 -0.12141653  0.15810530</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PCA &lt;-<span class="st"> </span><span class="kw">prcomp</span>(wodehouse[,<span class="op">-</span><span class="dv">1</span>])
PCA</code></pre></div>
<pre><code>## Standard deviations (1, .., p=9):
## [1] 0.0116449044 0.0063365624 0.0042954683 0.0035302457 0.0024647985
## [6] 0.0020861643 0.0013620747 0.0008093498 0.0003556737
## 
## Rotation (n x k) = (9 x 9):
##                 PC1         PC2          PC3         PC4         PC5
## гарольд  0.03548428 -0.19663999  0.075686879 -0.03368713  0.05890242
## гасси    0.08477226  0.51351224  0.134539726  0.05377012  0.65708710
## далия   -0.11013760  0.09840259 -0.388433965 -0.43335718 -0.21220875
## дживс   -0.48849572  0.10100883 -0.148787895 -0.57991681  0.28388407
## мадлен   0.12377778  0.18961709  0.020354106  0.32039042  0.22010871
## оутс    -0.04712363 -0.06751616  0.004473342  0.20678545 -0.34253505
## спод     0.09814424  0.55844483  0.599469737 -0.29899851 -0.45659562
## стиффи   0.05838698 -0.56967373  0.609313517 -0.30930782  0.24922420
## сэр     -0.84274152  0.02915765  0.268496830  0.37601904 -0.05266838
##                 PC6         PC7         PC8         PC9
## гарольд  0.14492413  0.11925658  0.73875236  0.60725660
## гасси    0.43845894  0.19560719  0.10480039 -0.18673960
## далия    0.65127401 -0.36616001 -0.12101985  0.14696227
## дживс   -0.43803831 -0.09265465  0.27430311 -0.19087430
## мадлен  -0.20367150 -0.85162955  0.09852740  0.14404733
## оутс     0.21240113 -0.13343752  0.55755002 -0.67773786
## спод    -0.09036398 -0.03379965  0.04752482  0.09847218
## стиффи   0.20775743 -0.24593603 -0.12571229 -0.15350747
## сэр      0.18108076 -0.01233863 -0.12141653  0.15810530</code></pre>
<p>Как читать полученное? Мы сменили оси координат и в новом пространстве (точно так же 9-мерном) мы можем перейти используя полученные значения:</p>
<p><span class="math display">\[PC1 = гарольд \times 0.03548428 + гасси \times 0.08477226 + далия \times -0.11013760 + дживс \times -0.48849572 +\]</span> <span class="math display">\[ + мадлен \times 0.12377778 + оутс \times -0.04712363 + спод \times 0.09814424 + стиффи \times 0.05838698 + сэр \times -0.84274152\]</span></p>
<p>Как полученные компоненты объясняют дисперсию в переменных?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(PCA)</code></pre></div>
<pre><code>## Importance of components:
##                            PC1      PC2      PC3     PC4      PC5      PC6
## Standard deviation     0.01164 0.006337 0.004295 0.00353 0.002465 0.002086
## Proportion of Variance 0.61713 0.182730 0.083970 0.05672 0.027650 0.019810
## Cumulative Proportion  0.61713 0.799860 0.883830 0.94055 0.968190 0.988000
##                             PC7       PC8       PC9
## Standard deviation     0.001362 0.0008093 0.0003557
## Proportion of Variance 0.008440 0.0029800 0.0005800
## Cumulative Proportion  0.996440 0.9994200 1.0000000</code></pre>
<p>Т. е. первые две компоненты объясняют почти 80 процентов дисперсии, это достаточно высокое значение, которое позволяет нам применять данный метод.</p>
<p>Дальнейшая визуализация возможна благодаря пакету <code>ggfortify</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggfortify)
<span class="kw">autoplot</span>(PCA,
         <span class="dt">shape =</span> <span class="ot">FALSE</span>,
         <span class="dt">loadings =</span> <span class="ot">TRUE</span>,
         <span class="dt">label =</span> <span class="ot">TRUE</span>,
         <span class="dt">loadings.label =</span> <span class="ot">TRUE</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="5_PCA_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Числа на этом графике — номера глав романа, красные линии — оси старых осей координат. Сам график называется биплот. Чем ближе друг к другустарые оси координат, тем больше скоррелированы переменные (вообще, косинус угла между ними равен коэфициенту корреляции между соответствующими переменными).</p>
<div class="parallax">

</div>
</div>
<div id="-" class="section level3">
<h3>5. Что дальше?</h3>
<ul>
<li>После того как преобразование сделано можно запскать стандартные методы регрессии, кластеризации и т. д.</li>
<li>можно использовать некоторые не затронутые в PCA переменные, для анализа в новом пространстве</li>
</ul>
<div class="parallax">

</div>
</div>
<div id="d----" class="section level3">
<h3>6. 3d пример от Ильи Щурова</h3>
<p><a href="http://math-info.hse.ru/f/2015-16/ling-mag-quant/lecture-pca.html#%D0%A2%D1%80%D1%91%D1%85%D0%BC%D0%B5%D1%80%D0%BD%D1%8B%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80">ссылка</a></p>
<div class="parallax">

</div>
</div>
<div class="section level3">
<h3>7. Евангелия</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gospels &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://goo.gl/mdBVVe&quot;</span>)</code></pre></div>
<div class="parallax">

</div>
</div>

<br><br><br>
<p><center> &copy; Г. Мороз 2018 с помощью RMarkdown. Исходный код на 
<a href="https://github.com/agricolamz/2018_data_analysis_for_linguists"> GitHub <img src="https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png"  style="width:30px;height:30px;border:0"></a></center> </p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
